### PR TITLE
Ignore any previously set profile when getting it from tokenInfo

### PR DESCRIPTION
**Pull request by Floby**
Just a single line change which solves the issue described in https://github.com/seawatts/ember-simple-auth-auth0/issues/30

I might add that tokenInfo is being deprecated by Auth0 and that we might want to use /userinfo instead.

### CODE REVIEW

**Comment by Floby** [comment]
> bloody semi

**Comment by seawatts** [comment]
This looks good. 👍 Can you rebase with develop?

**Comment by seawatts** [comment]
Closing due to https://github.com/seawatts/ember-simple-auth-auth0/pull/33

**Comment by Floby** [comment]
Sorry I missed that last message. but hey! thanks

**Comment by seawatts** [comment]
No big deal 👍

**Pull request closed without merging**
