### PR TITLE
fix: correct Lock object init/fn call order of operations

### LINKED ISSUE #56: Uncaught TypeError: Cannot call a class as a function when using auth0-lock authenticator
Getting this error & stack trace when trying to authenticate using the auth0-lock authenticator (using develop branch because of the semver fix):

```
Uncaught TypeError: Cannot call a class as a function
    at _classCallCheck (http://localhost:4200/assets/vendor.js:147441:100)
    at Auth0Lock (http://localhost:4200/assets/vendor.js:147473:6)
    at eval (eval at evaluate (:85:21), <anonymous>:1:29)
    at Class.getAuth0LockInstance (http://localhost:4200/assets/vendor.js:266406:7)
    at exports.default.Service.extend.showLock (http://localhost:4200/assets/vendor.js:266347:26)
    at initializePromise (http://localhost:4200/assets/vendor.js:69126:7)
    at new Promise (http://localhost:4200/assets/vendor.js:69614:33)
    at Class.showLock (http://localhost:4200/assets/vendor.js:266346:14
    at Class.authenticate (http://localhost:4200/assets/vendor.js:266034:33)
    at Class.authenticate (http://localhost:4200/assets/vendor.js:267800:41)
```

I traced the issue to these changes here https://github.com/seawatts/ember-simple-auth-auth0/commit/030761b25c64dd71f578a64db88ca742d75b0e29#diff-8aa2463356ae0d08be5bee9012675cedR145

coincidentally caused by the semver fix 😛 

It appears that the function call itself `get(this, '_auth0Lock')(clientID, domain, options)` is being evaluated before the `new` keyword is evaluated/the object is initialized, causing `_classCallCheck` to fail every time

In the console, I threw a debugger above this line and did:

`a = get(this, '_auth0Lock');`

and then:

`a(clientID, domain, options);`

Which evaluated in the right order and seemed to work. Pretty sure this is the issue. 

Cheers!

### PR DESCRIPTION
**Pull request by jmar910**
Fixes #56

### CODE REVIEW

**Comment by seawatts** [comment]
Thanks for submitting this! I'd like to keep these there so I can mock them out in tests in the future.

**Comment by jmar910** [comment]
@seawatts is that not what I have? Or do you mean I should change the name of the variable to suffix with `Constructor`?

**Comment by seawatts** [comment]
You should probably add the Constructor part to it to avoid naming collisions with the global imports

**Comment by jmar910** [comment]
Oh duh, I see 👍

**Comment by jmar910** [comment]
done and done 🎉

**Comment by seawatts** [comment]
Thanks again!!

**Pull request merged**
